kind: Service
apiVersion: v1

metadata:
  name: django-svc
  namespace: django-ns

spec:
  selector:
    app: django-notes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 

